### ISSUE TITLE
Class 'ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\DcaReadingDataDefinitionBuilder' not found

### ISSUE THREAD

**Issue by tristanlins** [bit3/contao-meta-palettes#32]
See https://github.com/bit3/contao-theme-plus/issues/89

**Comment by rflx** [comment]
I'm getting a blank screen in FE & BE updating MetaPalettes 1.8.1 to 1.9.0 in Contao 3.4.0 via composer. Is it true that MetaPalettes 1.9.0 is defect?

**Comment by discordier** [comment]
Quote @tristanlins https://github.com/bit3/contao-theme-plus/issues/89#issuecomment-69200593
> @discordier why is the class `DcaReadingDataDefinitionBuilder` required by meta palettes when no DCG is installed?

This is why MetaPalettes requires the `DcaReadingDataDefinitionBuilder`
https://github.com/bit3/contao-meta-palettes/blob/7cdf0640f70c70987cafc95609faa2b85a897b28/src/MetaPalettesBuilder.php#L33:

And this is why it is loaded even if not needed at all:
https://github.com/bit3/contao-meta-palettes/blob/a9255a37f947e067de7a1b86ce7a9d6e72e59f19/contao/config/config.php#L49.

**Comment by tristanlins** [comment]
Is the second `class_alias` necessary?
https://github.com/bit3/contao-meta-palettes/blob/a9255a37f947e067de7a1b86ce7a9d6e72e59f19/contao/config/config.php#L50

The event registration should be enough?!

**Comment by discordier** [comment]
No, it is not and the first one should be moved into an autoloader function as discussed.

**Comment by tristanlins** [comment]
Fixed in version 1.9.1

**Comment by bytehead** [comment]
:+1: Thanks!

**Comment by design23** [comment]
Hi, eben die aktuelle Nightly von MM installiert, Fehler besteht noch:

Fatal error: Class 'Bit3\Contao\MetaPalettes\MetaPalettes' not found in system/modules/core/library/Contao/System.php on line 110

Name                                                  Version                 Last modification
=================================================================================================
http://bit3.de
bit3/contao-meta-palettes                             1.9.1                   2015-01-12 06:27:47
-------------------------------------------------------------------------------------------------

http://c-c-a.org/
contao-community-alliance/backports-initialize-system dev-develop @ f5830e    2014-12-04 08:50:33
contao-community-alliance/dc-general                  dev-develop @ c3b7ee    2015-01-13 05:30:57
contao-community-alliance/dependency-container        dev-develop @ 1da3ad    2014-12-04 06:08:29
contao-community-alliance/event-dispatcher            dev-develop @ d2da54    2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings      dev-contao-3.2 @ 36eee0 2014-11-08 18:39:45
contao-community-alliance/translator                  dev-develop @ 02feca    2014-06-05 08:57:37
-------------------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                            0.5.4                   2014-02-05 22:52:54
-------------------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                        dev-master @ 23210e     2015-01-11 19:26:38
-------------------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                         1.0.2                   2014-02-07 22:35:55
-------------------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard                    dev-dev @ ae91b5        2014-11-20 11:57:11
-------------------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                            dev-tng @ 06e094        2014-12-16 05:18:37
metamodels/attribute_checkbox                         dev-tng @ cca087        2014-12-17 05:49:52
metamodels/attribute_combinedvalues                   dev-tng @ 58cfd6        2014-11-12 17:48:31
metamodels/attribute_country                          dev-tng @ 60a1e8        2015-01-10 02:27:54
metamodels/attribute_decimal                          dev-tng @ e5bba0        2014-12-16 00:35:07
metamodels/attribute_file                             dev-tng @ de070f        2014-11-12 17:45:51
metamodels/attribute_langcode                         dev-tng @ a3200d        2014-12-16 00:31:15
metamodels/attribute_longtext                         dev-tng @ 33e145        2014-11-07 15:00:37
metamodels/attribute_numeric                          dev-tng @ 4362ae        2014-11-20 12:50:06
metamodels/attribute_rating                           dev-tng @ 021ede        2014-11-20 12:37:30
metamodels/attribute_select                           dev-tng @ 477d53        2014-12-21 20:32:51
metamodels/attribute_tabletext                        dev-tng @ 23ee9c        2014-12-01 14:23:20
metamodels/attribute_tags                             dev-tng @ ba2749        2015-01-10 18:09:07
metamodels/attribute_text                             dev-tng @ 4f551c        2014-12-18 18:29:58
metamodels/attribute_timestamp                        dev-tng @ 247563        2014-11-20 12:46:00
metamodels/attribute_translatedalias                  dev-tng @ e70a89        2014-12-04 02:28:26
metamodels/attribute_translatedcheckbox               dev-tng @ e12e48        2015-01-10 04:46:53
metamodels/attribute_translatedcombinedvalues         dev-tng @ 445ab5        2015-01-10 08:20:05
metamodels/attribute_translatedfile                   dev-tng @ ec28cc        2015-01-06 06:18:32
metamodels/attribute_translatedlongtext               dev-tng @ fb21fb        2014-12-21 20:12:33
metamodels/attribute_translatedselect                 dev-tng @ 46e336        2014-12-11 18:54:34
metamodels/attribute_translatedtabletext              dev-tng @ 07ac20        2015-01-06 06:24:09
metamodels/attribute_translatedtags                   dev-tng @ 5ec0ee        2015-01-08 04:02:57
metamodels/attribute_translatedtext                   dev-tng @ f2ad30        2014-12-21 20:14:42
metamodels/attribute_url                              dev-tng @ ffd05a        2014-12-21 20:31:03
metamodels/bundle_all                                 dev-master @ f58927     2013-10-01 20:03:31
metamodels/bundle_attributes                          dev-master @ 058e26     2014-02-03 14:19:34
metamodels/bundle_filter                              dev-master @ 45d9cf     2013-05-03 07:16:44
metamodels/bundle_nontranslated                       dev-master @ 5f2b3f     2014-02-17 14:37:26
metamodels/bundle_translated                          dev-master @ 4bc0c1     2014-02-17 14:34:39
metamodels/core                                       dev-tng @ 627e4d        2015-01-09 13:58:56
metamodels/filter_checkbox                            dev-tng @ 230a0e        2014-11-11 17:30:48
metamodels/filter_fromto                              dev-tng @ db880c        2014-11-07 20:57:14
metamodels/filter_range                               dev-tng @ bf0103        2014-08-14 02:16:24
metamodels/filter_select                              dev-tng @ 597806        2015-01-10 05:37:20
metamodels/filter_tags                                dev-tng @ b97cb2        2015-01-10 05:36:54
metamodels/filter_text                                dev-tng @ 6df9de        2015-01-13 04:37:56
-------------------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                         1.1.x-dev @ bc2fc1      2014-04-20 07:24:09
-------------------------------------------------------------------------------------------------

http://symfony.com
symfony/event-dispatcher                              2.7.x-dev @ eab88a      2015-01-09 06:51:41
symfony/expression-language                           2.7.x-dev @ e11e60      2015-01-09 06:51:41
-------------------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder                 dev-develop @ 5f8997    2014-09-20 03:38:06

**Comment by discordier** [comment]
Es gab noch ein Problem im Nightly builder.
Habe es soeben von Hand nochmal gebaut und sehe die Klasse in der enthaltenen autoload.php, Das Problem sollte nun hoffentlich gaenzlich behoben sein.

**Comment by design23** [comment]
Sollte das mit dem jetzt verfügbaren Nightly behoben sein? Eben über eure Seite einen neuen Nightly runtergeladen, alle alten Dateien + Ordner gelöscht, Nightly installiert und Installtool laufen lassen. Nun lädt weder Front- noch Backend... 3 Browser getestet -> alle laden und laden und laden... ohne Ergebnis oder Fehlermeldung.

**Comment by tristanlins** [comment]
Klingt ja fast nach einem OPcode Cache failure...

**Comment by design23** [comment]
Hab jetzt mal den opcache in MAMP über die php.ini deaktiviert. Nun rennt das ganze wahlweise in einen Timeout oder generiert nur einen weißen Bildschirm im BE... any ideas?

**Comment by discordier** [comment]
Klingt nach endlosrekursion. Schwer zu sagen was da schief laeuft.
Steht irgendwas in den logs?

**Comment by tristanlins** [comment]
@discordier da hatte ich auch schon dran gedacht, aber dann müsste er doch in den "max call stack" rein rennen?!

**Comment by discordier** [comment]
@tristanlins kann auch eine nicht deterministische Schleife sein:
```php
while (true) {
}
```
wobei true hier logischerweise nur Platzhalter ist fyr einen "immer wahren" Ausdruck.
Ich hab jedoch keine Ahnung wo der sich rumtreiben koennte.
Da muss man wohl mal mit xdebug oder var_dump()+die() anrycken.

**Comment by design23** [comment]
Nachdem ich memory und die execution time übelst hoch gesetzt hatte, hab ich es geschafft ein error.log file mit sagenhaften 1,75GB zu erzeugen ;)

Und ja, da schleift was:

#255 /.../system/modules/metamodels/classes/src/MetaModels/MetaModel.php(412): MetaModels\Attribute\Tags\MetaModelTags->getDataFor(Array)
#256 /.../system/modules/metamodels/classes/src/MetaModels/MetaModel.php(463): MetaModels\MetaModel->fetchAdditionalAttributes(Array, Array, Array)
#257 /.../system/modules/metamodels/classes/src/MetaModels/MetaModel.php(689): MetaModels\MetaModel->getItemsWithId(Array, Array)
#258 /.../system/modules/metamodelsattribute_tags/classes/src/MetaModels/Attribute/Tags/MetaModelTags.php(427): MetaModels\MetaModel->findByFilter(Object(MetaModels\Filter\Filter), 'id')

**Comment by discordier** [comment]
Hast du einen rekursiven Bezug zwischen deinen MetaModels?

**Comment by design23** [comment]
Also ich habe mehrere MM mit n:m Relationen. Was genau meinst Du mit rekursivem Bezug?

**Comment by discordier** [comment]
Dass die MetaModels sich im Kreis herum referenzieren.
